plugins:
  - jekyll-seo-tag


title: LucidDreamer
tagline: Domain-free Generation of 3D Gaussian Splatting Scenes
url: anonymous-luciddremaer.github.io
author:
  name: Jaerin Lee
  url: https://jaerinlee.com

